
* formule

- ticket :: "Buongiorno/Buonasera, sono @nome@, la chiamo dall'Italia per conto di Aruba S.p.A.. Vedo che ha aperto una richiesta di assistenza .."
- chiamata :: "Buongiorno/Buonasera, sono @nome@ di Aruba le rispondo dall'Italia. Come posso aiutarla?"
- attesa :: "Posso metterla un attimo in attesa? / La ringrazio per l'attessa."


  "Troverà un messaggio di risoluzione assistenza a cui poter cliccare il pulsante =Sì, ho risolto.= forse le chiederanno una valutazione sulla mia assistenza. La ringrazio, è stato un piacere."

  - www.pec.it supporto => accedi => le tue richieste ..


** IVR (Interactive Voice Response)

- _crossline_centax: prevendita
- _anagrafica_centax: acquisti, rinnovi, pagamenti
- _assistenza_centax: modifica dati, assistenza technica


- modifica dati login => contattare TL
- vendita: informazioni e modalità di acquisto servizio ..


- dispatch => hosting (dominio privato), fatturazione (fra cui DocFly), cloud
- operatore => pec, spid, firma (fra cui smartcard, non ha il rinnovo automatico), billing


- fibra => connettività
- rentri => certifiedplat_assistenza_transcom


** CMS mistery garante privacy

- aprire sempre una nuova richiesta come una sottocategoria di: privacy, dati personali e .. (ticket => modificare la sezione servizi)
- inoltrare: privacy_change / account_anagrafica_privacy
- "le ho aperto una richiesta dedicata, riceverà una risposta da un opereratore che tratta queste tematiche quanto prima"
- aruba deve rispondere entro 30g a queste richieste
- eventuale email per contatto anonimo: privacy@staff.aruba.it


* www.pec.it

"nuova raccomandata con ricevuta di ritorno", www.inipec.gov.it: indice nazionale indirizzi

=> convenzioni


- .xml: struttura messaggio
- .eml: messaggio inviato
- .p7s: certificati


- ric. accettazione: max 5h (presa in carico dal gestore del mittente)
- ric. consegna: max 12h + 12h
- peclog: 30m


- conservazione digitale :: garantisce la conformità alle norme di legge per la conservazione e l'esigibilità dei messaggi (allegati compresi)
- problemi in prevendita :: crossline_assistenza_aruba => mandare ticket ad un tl su teams
- standard europei (REM: Registered Electronic Mail) :: possibile adeguarsi, non ancora obbligatorio


** ticket (richiesta di assistenza)

max1 per volta => spezzare la risoluzione


- centax => gestisci
- aruba, competente => fornire assistenza
- aruba, incompetente =>
  - attesa reparto interno / attesa fornitore => solecito, mandare ticket ad un tl su teams
  - proposta soluzione / attesa utente => feedback cliente, riportare quanto comunicato dal clt
- _ => tranferisci


- scalo a tl :: "scalo per verifiche"


** partner/inoltroko: mappare activity (ticket: mdc partner)

"l'indirizzo Pec @indirizzo@ non l'ha acquistato direttamente dal portale pec.it, pertanto troverà un'assistenza dedicata al .."


- supportotitolari.aruba.it
- @archiworldpec.it: 0575050013
- @ingpec.eu: 0575050014


- numero verde(=> gratuito) fibra: 800903633


-----


** webmail.pec.it (pec/recuperopwpec)

messaggi peo non danno notifica


- webmail => transazione webmail


** modificacontatti.pec.it (changecontact aruba)

- webmail => impostazioni => email e cellulare
- accedi alla pec => pw dimenticata => non puoi più accedere a questo indirizzo email? modificalo


- contatti pga => conferma titolarità leg.rapp.


** [[https://guide.pec.it/posta-pec/configurare-casella-pec/configurare-casella-pec-programma-posta.aspx][configurazione-client]]


-----


** areaclienti.pec.it (pec/user/creauser)

tentare di modificare l'email di contatto tramite l'sms.
(usare username per rinnovare la casella quando la 2fa è attiva).


- contatti username => conferma documenti del nuovo titolare
- fare verificare all'utente lo stato di cancellata (posso dire solo la casella è scaduta da più di 90g)
- riacquisto solo alle stesse condizioni
- fare annullare gli ordini all'utente
- aumenta spazio (intralogin => username)
- disattivare il rinnovo automatico se non compare il pulsante rinnova
- rinnovo intraogin => usare username


** modifica titolare => username / modifica titolare / mortis causa

- intralogin => usare pec
- conferma identità pendente / confermata  => usare username


- pec in convenzione, modulo di richiesta e stesso cf => extranet: cambio propietà
- => reset storico accessi, reimpostare pw


** correzione dati errati (no servizio)

i codici rcd li vede solo account_angrafica


  - solo pec =>
    - nome, cognome => extranet, aggiungere nota con ticket
    - ragione sociale, residenza italiana => username => cambio dati (modifica anche spa)
    - _ => inoltrare pec_change_aruba
  - anche altri servizi => inoltrare account_anagrafica / account_anagrafica_cambio_dati


** extranet username

- stato trasferita => partner

- username cancellata => girare ad account_anagrafica
- username e pec non corrispondono => girare a pec_change
- username non attiva => procedo indicando il nome con un altra username valida


- visualizzare carte
- accesso trust


-----


** pagamenti e fatture => inserimento dati pagamento

la fattura arriva al indirizzo peo indicato entro il 15 del mese successivo alla registrazione del pagamento


- bollettino bianco (istituti privati): cro (no cro => n.ordine n.ordine), n.ordine, importo
- bollettino premarcato (ha il timbro), consigliato perché minimiza gli errori
- bonifico > 72h LAVORATIVE => scala a tl
- bonifico > 500€ => inolrare pagamenti_billing_aruba
- bollettino > 72h LAVORATIVE => inolrare pagamenti_billing_aruba


- contabilità => imposta pagamento (usare virgola)
- aggiungere nota: ticket, commento, n. ordine


stato ordine => pec_change_aruba: ordine pagato ma non evaso


cro/trn/sct..


** pagamenti.aruba.it (n.ordine:carte/paypal)

bill-inserimento..


- contabilità => visualizza transazioni => transazioni (n.ordine)
- cms billing => procedure => codici di errore


bonifico:
#+begin_example
Intestato a: Aruba S.p.A.
IBAN: IT55C0538771335000042125809
Causale: Pagamento ordine ...
Swift/BIC: BPMOIT22XXX
BPER Banca S.p.A. agenzia Bibbiena Stazione
#+end_example


** modifica email spa => billing aruba

modifica dati fatturazione => codice destinatario (SDI: sistema di intescambio)

- p.iva <=> tipologia di utente


** visualizare fatture, fatture.aruba.it (formato .xml)

il cassetto fiscale dell'agenzia delle entrate va attivato manualmente


- contabilità => visualizza fatture => n.ordine
- cambio dati di fatturazione, correzione .. => pagamenti_billing_aruba


-----


** cambio nome

- impostazioni casella pec => conversazione: cambio nome
- risposta inoltrata a pagamenti_billing_aruba


** disdetta conservazione digitale

- servizio aggiuntivo => inoltrare pec_change_aruba (indicare al cliente di attendere una risposta)


** disconoscimento pagamento

- disconoscimento pagamento
- alla risposta => inoltrare pagamenti_billing_aruba


** diritto di recesso, mortis causa (14g intesi dall'attivazione)

auth alta => scalo a tl, motivo altro


- informazione cancellazione definitiva pec => mortis causa
- rimborso => inoltro billing_aruba


- consegueze cancellazione Pec :: come indicato, una volta cancellata la casella Pec, non sarà più possibile recuperare i messaggi


-----


** conferma id

e-security => pec eu consumer (stato: ko, in lavorazione, nuova documentazione)


- cf: legale rappresentante
- azienda: visura camerale
- associazoni: verbale assembleare


(più recente del ko e non più vecchia di 30giorni)


** richiesta log applicativi

auth alta: verifica in 2 pass. => log applicativi => inoltrare a pec_request_aruba


** richiesta da autorità: PRO11271


** comunicazioni aruba (@staff.aruba.it, 05750505/05ricontatto)

"il servizio è sempre attivo"

- pagamenti e fature => phishing


** assistenza.aruba.it (assistenza autenticata)


-----

** incident

apri ticket => incident => codice


** altro (non risolto => note complete)


- verificare p.soluzioni mensili
- cambia credenziale => salva
- cambio lingua => altre informazioni


- 626: 15min, pausa bagno


** fine turno

- rilasciare: lavorazione, feedback
- tenere: attesa utente, pianificato
- mai rilasciare: mancata accettazione


