
* formule

- ticket :: "Buongiorno/Buonasera, sono @nome@, la chiamo dall'Italia per conto di Aruba S.p.A.. Vedo che ha aperto una richiesta di assistenza .."
- chiamata :: "Buongiorno/Buonasera, sono @nome@ di Aruba le rispondo dall'Italia. Come posso aiutarla?"
- attesa :: "La posso mettere un attimo in attesa? / La ringrazio per l'attessa."
- chiusura :: "Come ultimo passaggio dovremmo chiudere la richiesta di assistenza."


  - apra la @peo@
  - www.pec.it supporto => accedi


  "a questo punto dovrebbe trovare un messaggio di risoluzione assistenza in cui poter cliccare il pulsante =Sì, ho risolto.= confermare. Vede: =La richiesta è stata chiusa=? La ringrazio, è stato un piacere."


* www.pec.it

"nuova raccomandata con ricevuta di ritorno", www.inipec.gov.it: indice nazionale indirizzi

=> convenzioni


- .xml: struttura messaggio
- .eml: messaggio inviato
- .p7s: certificati

- conservazione digitale :: garantisce la conformità alle norme di legge per la conservazione e l'esigibilità dei messaggi (allegati compresi)
- problemi in prevendita :: crossline_assistenza_aruba => mandare ticket ad un tl su teams
- standard europei (REM: Registered Electronic Mail) :: possibile adeguarsi, non ancora obbligatorio


** ticket (richiesta di assistenza)

max1 per volta => spezzare la risoluzione


- centax => gestisci
- billing_aruba => sollecito, mandare ticket ad un tl su teams
- aruba: lun-ven 8:30-12:45, 14:30-17:30 => conference => tranferisci
- aruba: fuori_orario => sollecito
- _ => tranferisci


- conference :: consultazione => rimanere in attesa => trasferisci o termina


** partner/inoltroko: mappare activity (ticket: mdc partner)

"l'indirizzo Pec @indirizzo@ non l'ha acquistato direttamente dal portale pec.it, pertanto troverà un'assistenza dedicata al .."


- supportotitolari.aruba.it
- @archiworldpec.it: 0575050013
- @ingpec.eu: 0575050014


-----


** webmail.pec.it (pec/recuperopwpec)

messaggi peo non danno notifica


- webmail => transazione webmail


** modificacontatti.pec.it (webmail => impostazioni => email e cellulare)

accedi alla pec => pw dimenticata => non puoi più accedere a questo indirizzo email? modificalo


- contatti pga => conferma titolarità leg.rapp.


** [[https://guide.pec.it/posta-pec/configurare-casella-pec/configurare-casella-pec-programma-posta.aspx][configurazione-client]]


-----


** areaclienti.pec.it (pec/user/creauser)

tentare di modificare l'email di contatto tramite l'sms.
(usare username per rinnovare la casella quando la 2fa è attiva).


- contatti username => conferma documenti del nuovo titolare
- fare verificare all'utente lo stato di cancellata (posso dire solo la casella è scaduta da più di 90g)
- riacquisto solo alle stesse condizioni
- fare annullare gli ordini all'utente
- aumenta spazio
- disattivare il rinnovo automatico se non compare il pulsante rinnova


** modifica titolare => username / modifica titolare / mortis causa

usare username se la pec ha un riconoscimento identità pendente (usare pec se intralogin => conferma tramite email)

- pec in convenzione, modulo di richiesta e stesso cf => extranet: cambio propietà
- => reset storico accessi


** correzione dati errati (no servizio)

i codici rcd li vede solo account_angrafica


- solo residenza italiana => username => cambio dati (modifica anche spa)
- _ =>
  - solo servizio pec => inoltrare pec_change_aruba
  - anche altri servizi => inoltrare account_anagrafica_cambio_dati


posso modificare il leg.rapp. da extranet, senza documentazione ma aggiungendo nota con ticket


** extranet username

username non attiva => procedo indicando il nome con un alra username valida
username cancellata => girare ad account anagrafica
username e pec non corrispondono => girare a pec_change


- visualizzare carte
- accesso trust


-----


** pagamenti e fatture => inserimento dati pagamento

la fattura arriva al indirizzo peo indicato entro il 15 del mese successivo alla registrazione del pagamento


- bollettino premarcato, consigliato perché minimiza gli errori (ha il timbro)
- bollettino bianco (istituti privati): cro (no cro => n.ordine n.ordine), n.ordine, importo
- bonifico > 72h lavorative => scala a tl
- bonifico > 500€ => inolrare pagamenti_billing_aruba


- contabilità => imposta pagamento (usare virgola)
- aggiungere nota: ticket, commento, n. ordine


** pagamenti.aruba.it (n.ordine/carte/paypal)

bil-inserimento..


- contabilità => visualizza transazioni => transazioni (n.ordine)
- cms billing => procedure => codici di errore


** modifica email spa => billing aruba


** visualizare fatture, fatture.aruba.it

il cassetto fiscale dell'agenzia delle entrate va attivato manualmente


- contabilità => visualizza fatture => n.ordine
- cambio dati fatturazione, correzione .. => pagamenti_billing_aruba


-----


** cambio nome

- impostazione casella pec => conversazione: cambio nome
- risposta inoltrata a pagamenti_billing_aruba


** disdetta conservazione digitale

- servizio aggiuntivo => inoltrare pec_change_aruba (indicare al cliente di attendere una risposta)


** disconoscimento pagamento

- amministrazione e pagamenti => disconoscimento pagamento
- alla risposta => inoltrare pagamenti_billing_aruba


** diritto di recesso, mortis causa

rimborso => inoltro billing_aruba


- auth alta => scalo a tl, motivo altro
- consegueze cancellazione Pec :: (tenga presente che se la casella Pec dovesse entrare in cancellazione non ci sarà più modo di recuperare i messaggi contenuti all'interno, pertanto la invito ad esportarli prima di tale data)


-----


** conferma id

e-security => pec eu consumer (stato: ko, in lavorazione, nuova documentazione)


- cf: legale rappresentante
- avienda: visura camerale
- associazoni: verbale assembleare


(più recente del ko e non più vecchia di 30giorni)


** richiesta log appliativi

auth alta: verifica in 2 pass. => log applicativi => inoltrare a pec_request_aruba


** richiesta da autorità: PRO11271


** comunicazioni aruba (@staff.aruba.it, 05750505/05ricontatto)

"il servizio è sempre attivo"

- pagamenti e fature => phishing


** assistenza.aruba.it (assistenza autenticata)


-----


** incident

apri ticket => incident => codice


** mystery garante privacy

- aprire sempre una nuova richiesta come una sottocategoria di: privacy, dati personali e .. (ticket => modificare la sezione servizi)
- inoltrare: privacy_change / account_anagrafica_privacy
- "le ho aperto una richiesta dedicata, riceverà una risposta da un opereratore che tratta queste tematiche quanto prima"
- aruba deve rispondere entro 30g a queste richieste
- eventuale email per contatto anonimo: privacy@staff.aruba.it


** cambia gruppo

fibra => connettività


- dispatch => hosting (dominio privato), fatturazione, cloud
- operatore => pec, spid, firma (fra cui smartcard), billing


-----

** tricks

- cambia credenziale => salva
- verificare p.soluzioni mensili
- cambio lingua => altre informazioni


- 626: 15min, pausa bagno


** fine turno

- rilasciare: lavorazione, feedback
- tenere: attesa utente, pianificato
- mai rilasciare: mancata accettazione


