
* formule

- ticket :: "Buongiorno/Buonasera, sono @nome@, la chiamo dall'Italia per conto di Aruba S.p.A.. Vedo che ha aperto una richiesta di assistenza .."
- chiamata :: "Buongiorno/Buonasera, sono @nome@ di Aruba le rispondo dall'Italia. Come posso aiutarla?"
- attesa :: "Posso metterla un attimo in attesa? / La ringrazio per l'attessa."


  "Le ho inviato una email con l'assistenza avuta assieme, riuscirebbe a cliccare su =Sì, ho risolto=.
  Forse le chiederanno chiedono una valutazione sulla MIA assistenza.
  La ringrazio, è stato un piacere!"

  - supporto => accedi => le tue richieste ..


** IVR (Interactive Voice Response)

- _crossline_centax: disdetta (no mortis causa), recesso, pw username
  - _anagrafica_centax: acquisti, rinnovi, pagamenti
- _assistenza_centax: modifica dati, assistenza technica


- modifica dati login => contattare TL


- dispatch => hosting (dominio privato), fatturazione (tra cui DocFly), cloud
- operatore => pec, spid, firma (tra cui smartcard, non ha il rinnovo automatico), billing


- fibra => connettività
- rentri => certifiedplat_assistenza_transcom
- scontrina => PRO11432A


- richieste anonime: essere generico, aggiungere cell.


* [[https://www.pec.it/][pec.it]]

"nuova raccomandata con ricevuta di ritorno"
- https://www.inipec.gov.it/web/guest/cerca-pec: Indice Nazionale Indirizzi PEC
- https://domiciliodigitale.gov.it/dgit/home/public/#!/home: Indice Nazionale dei Domicili Digitali


=> convenzioni


- .xml: struttura messaggio
- .eml: messaggio inviato
- .p7s: certificati


- ric. accettazione: max 5h (presa in carico dal gestore del mittente)
- ric. consegna: max 12h + 12h
- peclog: 30m


- conservazione digitale :: garantisce la conformità alle norme di legge per la conservazione e l'esigibilità dei messaggi (allegati compresi)
  - copia in da salvare => 72h => conservazione digitale => esibisci
- standard europei (REM: Registered Electronic Mail) :: possibile adeguarsi, non ancora obbligatorio
- AgID :: agenzia per l'italia digitale
- eIDAS :: electronic IDentification, Authentication and trust Services


** ticket (richiesta di assistenza)

max1 per volta => spezzare la risoluzione


- centax => gestisci
- aruba, competente => fornire assistenza
- aruba, incompetente =>
  - attesa reparto interno / attesa fornitore => solecito, mandare ticket ad un tl su teams
  - proposta soluzione / attesa utente => feedback cliente, riportare quanto comunicato dal clt
- _ => tranferisci


- aruba, chiusa: apri una nuova ed aggiungi n. ticket in nota


- scalo a tl :: "scalo per verifiche"


** partner/inoltroko: mappare activity (ticket: mdc partner)

"questo indirizzo non l'ha acquistato direttamente dal portale pec.it, pertanto trova un'assistenza dedicata al .."


- supportotitolari.aruba.it
- @archiworldpec.it: 0575050013
- @ingpec.eu: 0575050014


- numero verde(=> gratuito) fibra: 800903633


-----


** webmail.pec.it (pec/recuperopwpec)

messaggi non pec non hanno notifiche per avvisi e report


- webmail => transazione webmail
- webamil => leggi fatture
- errori utilizzo webmail => mancata visualizzazione ricevute


** modificacontatti.pec.it (changecontact aruba)

- webmail => impostazioni => email e cellulare
- accedi alla pec => pw dimenticata => non puoi più accedere a questo indirizzo email? modificalo


- contatti pga => conferma titolarità leg.rapp. (id verificata => no invio documenti)


** [[https://guide.pec.it/posta-pec/configurare-casella-pec/configurare-casella-pec-programma-posta.aspx][configurazione-client]]


-----


** areaclienti.pec.it (pec/user/creauser)

tentare di modificare l'email di contatto tramite l'sms.
(usare username per rinnovare la casella quando la 2fa è attiva).


- modifica dati iscrizione associati allo username @aruba.it PEC => modifica dati online account aruba


- contatti username => conferma documenti del nuovo titolare
- fare verificare all'utente lo stato di cancellata
  - impostazioni casella pec: richiesta log legali ..
- .. acquisto .. (riacquisto solo alle stesse condizioni, => quelle in convezione non possono essere riacquistate)
- fare annullare gli ordini all'utente
- upgrade spazio (giorni rimanenti), rinnovo (attivato subito, pagato solo per gli anni successivi)
  - intralogin => usare username
- compare il pulsante rinnova => disattivare il rinnovo automatico


** modifica titolare => username / modifica titolare / mortis causa

- intralogin => usare pec
- conferma identità pendente / confermata  => usare username


- pec in convenzione, modulo di richiesta e stesso cf => extranet: cambio propietà
- => reset storico accessi, reimpostare pw


** correzione dati errati (no servizio)

  - solo pec =>
    - nome, cognome => extranet, aggiungere nota con ticket
    - ragione sociale, residenza italiana => username => cambio dati (modifica anche spa)
    - _ => inoltrare pec_change_aruba
  - anche altri servizi => inoltrare account_anagrafica / account_anagrafica_cambio_dati


i codici rcd li vede solo account_angrafica in 24/48h (per velocizzare posso inviarli in chat ad un tl)


** extranet username

- stato trasferita => partner

- username cancellata => girare ad account_anagrafica
- username e pec non corrispondono => girare a pec_change
- username non attiva => procedo indicando il nome con un altra username valida


- visualizzare carte
- accesso trust
- sezione volture


-----


** pagamenti e fatture => inserimento dati pagamento

la fattura arriva al indirizzo peo indicato entro il 15 del mese successivo alla registrazione del pagamento


verificare: IT55C0538771335000042125809, data


- bollettino bianco (istituti privati): cro (no cro => n.ordine n.ordine), n.ordine, importo
- bollettino premarcato (ha il timbro), consigliato perché minimiza gli errori
- bonifico > 72h LAVORATIVE => scala a tl
- bonifico > 500€ => inolrare pagamenti_billing_aruba
- bollettino > 72h LAVORATIVE => inolrare pagamenti_billing_aruba
- bolletino lispay => puntolis, recupera ricevuta


- contabilità => imposta pagamento (usare virgola) [è possibile indicare il n. di ordini]
- aggiungere nota: ticket, commento, n. ordine


stato ordine => pec_change_aruba: ordine pagato ma non evaso


cro/trn/sct..


** pagamenti.aruba.it (n.ordine:carte/paypal)

bill-inserimento..


- contabilità => visualizza transazioni => transazioni (n.ordine)
- cms billing => procedure => codici di errore


- plafond carta =>  limite massimo di spesa


bonifico:
#+begin_example
Intestato a: Aruba S.p.A.
IBAN: IT55C0538771335000042125809
Causale: Pagamento ordine ...
Swift/BIC: BPMOIT22XXX
BPER Banca S.p.A. agenzia Bibbiena Stazione
#+end_example


** modifica email spa => billing aruba

modifica dati fatturazione => codice destinatario (SDI: sistema di intescambio)

- p.iva <=> tipologia di utente (persona giuridica)
- PA (verificabili sull'IPA) possono pagare solo l'imponibili => ci inviano l'impegno di pagamento
- aziende collaboranti con le PA (verificabili sul sito DIPARTIMENTO DELLE FINANZE) => copio la striscia verde e la inserisco nelle note della richiesta di assistenza

 - CIG :: codice alfanumerico di 10 cifre che identifica la transazione di una PA


** visualizare fatture, fatture.aruba.it (formato .xml)

il cassetto fiscale dell'agenzia delle entrate va attivato manualmente


- contabilità => visualizza fatture => n.ordine (posso inviarla anche ad una email differente)
- cambio dati di fatturazione, correzione .. => indicare in nota il n. fattura, "cambio dati di fatturazione, invio fattura" => pagamenti_billing_aruba
- extranet: copia dati faturazione da sx a dx


-----


** cambio nome

- impostazioni casella pec => conversazione: cambio nome
- risposta inoltrata a pagamenti_billing_aruba


** disdetta conservazione digitale

- servizio aggiuntivo / conservazione => inoltrare pec_change_aruba (indicare al cliente di attendere una risposta)


** disconoscimento pagamento

- disconoscimento pagamento
- alla risposta => inoltrare pagamenti_billing_aruba


** disdetta (mortis causa) / recesso

- disdetta(PRO8734A) :: immediata, no rimborso
  - mdc "informazioni cancellazioe definitiva pec" (mortis causa)
  - auth alta: sms "cancelazione immediata e definitiva della casella .."
  - escalation tl: "non desidera backup, non desidera rimborso"
- recesso(PRO15138A) :: non immediata, vuole rimborso
  - mdc: ".. entro/olre 14g" (dall'attivazione)
  - "come da contatto telefonico la invito a rispondere alla presente comunicazione confermando la volontà di recedere dal servizio @NOME SERVIZIO@ con numero ordine @NUMERO di ORDINE@. La conferma è necessaria per poter evadere la richiesta di recesso.Le ricordo che, in caso di recesso, il servizio verrà cancellato con conseguente perdita dei dati. La invito pertanto a recuperare eventuali contenuti prima di confermare la richiesta.
    @Le segnalo inoltre che verranno applicate spese di lavorazione pari a 10 €, che saranno trattenute dall’importo da rimborsare@".
  - pec PF attivate < 14g => rimborso totale
  - standard 12.08€ < 1m; pro 30.50€ < 7m; premium 48.80€ < 9m => rimborso - 10€
  - _ => no rimborso
  - escalation tl


-----


** conferma id

e-security => pec eu consumer (stato: ko, in lavorazione, nuova documentazione)


- cf: legale rappresentante
- azienda: visura camerale
- associazoni: verbale assembleare


(più recente del ko e non più vecchia di 30giorni)


** richiesta log applicativi

auth alta: verifica in 2 pass. => log applicativi => inoltrare a pec_request_aruba


** richiesta da autorità: PRO11271


** comunicazioni aruba (@staff.aruba.it, 05750505/05ricontatto)

"il servizio è sempre attivo (siamo sempre aperti)"

- pagamenti e fature => phishing


** assistenza.aruba.it (assistenza autenticata)


-----

** incident

equivale ad: attesa reparto interno

apri ticket => incident => codice


** CMS mistery garante privacy

- aprire sempre una nuova richiesta come una sottocategoria di: privacy, dati personali e .. (ticket => modificare la sezione servizi)
- inoltrare: privacy_change / account_anagrafica_privacy
- "le ho aperto una richiesta dedicata, riceverà una risposta da un opereratore che tratta queste tematiche quanto prima"
- aruba deve rispondere entro 30g a queste richieste
- eventuale email per contatto anonimo: privacy@staff.aruba.it


** altro (non risolto => note complete)

- verificare p.soluzioni mensili
- cambia credenziale => salva
- cambio lingua => altre informazioni


- 626: 15min, pausa bagno


** fine turno

- rilasciare: lavorazione, feedback
- tenere: attesa utente, pianificato
- mai rilasciare: mancata accettazione


