* formule

- ticket :: "Buongiorno/Buonasera, sono @nome@, la chiamo dall'Italia per conto di Aruba. Vedo che ha aperto una richiesta di assistenza .."
- chiamata :: "Buongiorno/Buonasera, sono @nome@ di Aruba le rispondo dall'Italia. Come posso aiutarla?"
- attesa :: "La metto un attimo in attesa .."
- chiusura :: "Le ho inviato una email di risoluzione con quello che abbiamo fatto, dovrebbe cliccare sul pulsante =Sì, ho risolto.= in modo da che io possa chiudere la richiesta di assistenza."

  "Ha confermato? Dovrebbe vedere: La richiesta è stata chiusa."


* www.pec.it

=> convenzioni


- .xml: struttura messaggio
- .eml: messaggio inviato
- .p7s: certificati


** ticket (richiesta di assistenza)

max1 per volta => spezzare la risoluzione


- centax => gestisci
- billing_aruba => sollecito, mandare ticket ad un tl su teams
- aruba: lun-ven 8:30-12:45, 14:30-17:30 => conference => tranferisci
- aruba: fuori_orario => sollecito
- _ => tranferisci


** partner/inoltroko: mappare activity (ticket: mdc partner)

"l'indirizzo Pec @indirizzo@ non l'ha acquistato direttamente dal portale pec.it, pertanto troverà un'assistenza dedicata al .."


- supportotitolari.aruba.it
- @archiworldpec.it: 0575050013
- @ingpec.eu: 0575050014


-----


** webmail.pec.it (pec/recuperopwpec)

- webmail => transazione webmail


** [[https://modificacontatti.pec.it][modificacontatti.pec.it]] (webmail => impostazioni => email e cellulare)

accedi alla pec => pw dimenticata => modifica contatto


- contatti pga => conferma titolarità leg.rapp.


** [[https://guide.pec.it/posta-pec/configurare-casella-pec/configurare-casella-pec-programma-posta.aspx][configurazione-client]]


-----


** areaclienti.pec.it (pec/user/creauser)

tentare dia modificare l'email tramite cell.


- (usare username per rinnovare quando 2fa attiva)
- contatti username => conferma documenti del nuovo titolare
- fare annullare gli ordini all'utente


** modifica titolare => modifica titolare

usare username se la pec ha un riconoscimento identità pendente


- => reset storico accessi


** correzione dati errati (no servizio)

- solo residenza italiana => username => cambio dati (modifica anche spa)
- solo residenza estero / altri dati =>
  - solo pec => inoltrare a pec_change_aruba
  - anche altri servizi => inoltrare a account_anagrafica_cambio_dati


** extranet username

- visualizzare carte
- accesso trust


-----


** pagamenti e fatture => inserimento dati pagamento

la fattura arriva al indirizzo peo indicato entro il 15 del mese successivo


- bollettino premarcato (ha il timbro)
- bollettino bianco (istituti privati): cro (no cro => n.ordine n.ordine), n.ordine, importo


- contabilità => imposta pagamento (usare virgola)
- aggiungere nota: ticket, commento, n. ordine


** pagamenti.aruba.it (n.ordine/carte/paypal)

- contabilità => visualizza transazioni => transazioni (n.ordine)
- cms billing => procedure => codici di errore


** modifica email spa => billing aruba


** fatture.aruba.it

contabilità => visualizza fatture => n.ordine


-----


** cambio nome

- impostazione casella pec => conversazione: cambio nome
- risposta inoltrata a pagamenti_billing_aruba


** disdetta conservazione digitale

- servizio aggiuntivo => inoltrare pec_change_aruba (indicare al cliente di attendere una risposta)


** disconoscimento pagamento

- amministrazione e pagamenti => disconoscimento pagamento
- alla risposta => inoltra pagamenti_billing_aruba


** diritto di recesso

- scalo a tl, motivo altro


-----


** conferma id

e-security => pec eu consumer (stato: ko, in lavorazione, nuova documentazione)


- cf: legale rappresentante
- avienda: visura camerale
- associazoni: verbale assembleare


(più recente del ko e non più vecchia di 30giorni)


** richiesta da autorità: PRO11271


** comunicazioni aruba (@staff.aruba.it, 05750505/05ricontatto)

pagamenti e fature => phishing


** assistenza.aruba.it (assistenza autenticata)


-----


** incident

apri ticket => incident => codice


** mystery garante privacy

- aprire sempre una nuova richiesta come una sottocategoria di: privacy, dati personali e .. (ticket => modificare la sezione servizi)
- inoltrare a: privacy_change / account_anagrafica_privacy
- "le ho aperto una richiesta dedicata, riceverà una risposta da un opereratore che tratta queste tematiche quanto prima"
- aruba deve rispondere entro 30g a queste richieste
- eventuale email per contatto anonimo: privacy@staff.aruba.it


** cambia gruppo

- dispatch => hosting, fatturazione, cloud
- operatore => pec, spid, firma (smartcard) billing


-----


** fine turno

- rilasciare: lavorazione, feedback
- tenere: attesa utente, pianificato
- mai rilasciare: mancata accettazione


